<?php
session_start();
include 'includes/db.php';

if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

if ($_SESSION['role'] !== 'Admin') {
    header("Location: dashboard.php");
    exit();
}

/* Validate event ID */
if (!isset($_GET['id']) || !is_numeric($_GET['id'])) {
    die("Invalid event ID.");
}

$eventId = (int) $_GET['id'];

/* Get event information */
$eventStmt = mysqli_prepare(
    $conn,
    "SELECT *
     FROM events
     WHERE event_id = ?
     LIMIT 1"
);

mysqli_stmt_bind_param($eventStmt, "i", $eventId);
mysqli_stmt_execute($eventStmt);

$eventResult = mysqli_stmt_get_result($eventStmt);
$event = mysqli_fetch_assoc($eventResult);

mysqli_stmt_close($eventStmt);

if (!$event) {
    die("Event report not found.");
}

/* Get participant list */
$participantStmt = mysqli_prepare(
    $conn,
    "SELECT
        registration_id,
        full_name,
        matric_no,
        email,
        phone,
        payment_method,
        payment_status,
        attendance_status
     FROM registrations
     WHERE event_id = ?
     ORDER BY full_name ASC"
);

mysqli_stmt_bind_param($participantStmt, "i", $eventId);
mysqli_stmt_execute($participantStmt);

$participantResult = mysqli_stmt_get_result($participantStmt);

$participants = [];

while ($participant = mysqli_fetch_assoc($participantResult)) {
    $participants[] = $participant;
}

mysqli_stmt_close($participantStmt);

/* Calculate participant statistics */
$totalParticipants = count($participants);
$totalAttended = 0;
$totalAbsent = 0;
$totalRegistered = 0;
$totalPaid = 0;
$totalPendingPayment = 0;
$totalFailedPayment = 0;

foreach ($participants as $participant) {
    if ($participant['attendance_status'] === 'Attended') {
        $totalAttended++;
    }

    if ($participant['attendance_status'] === 'Absent') {
        $totalAbsent++;
    }

    if ($participant['attendance_status'] === 'Registered') {
        $totalRegistered++;
    }

    if ($participant['payment_status'] === 'Paid') {
        $totalPaid++;
    }

    if ($participant['payment_status'] === 'Pending Verification') {
        $totalPendingPayment++;
    }

    if ($participant['payment_status'] === 'Failed') {
        $totalFailedPayment++;
    }
}

$attendanceRate = $totalParticipants > 0
    ? round(($totalAttended / $totalParticipants) * 100)
    : 0;

/* Report information */
$generatedBy = $_SESSION['name'] ?? 'CampusEvent Administrator';
$generatedDate = date("d F Y, h:i A");

$reportNumber = "EVT-" . str_pad(
    $eventId,
    4,
    "0",
    STR_PAD_LEFT
);

$reportStatus = !empty($event['report_status'])
    ? $event['report_status']
    : 'Pending';

$statusClass = strtolower(
    str_replace(' ', '-', $reportStatus)
);

$posterPath = "";

if (!empty($event['poster'])) {
    $posterPath = "assets/posters/" . rawurlencode($event['poster']);
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
        <?php echo htmlspecialchars($reportNumber); ?>
        | Event Report
    </title>

    <link rel="stylesheet" href="assets/css/report.css?v=<?php echo time(); ?>">
</head>

<body>

    <div class="report-toolbar">

        <a href="report_detail.php?id=<?php echo $eventId; ?>" class="report-back-button">
            Back
        </a>

        <button type="button" class="report-print-button" onclick="window.print()">
            Print / Save PDF
        </button>

    </div>

    <main class="report-page">

        <header class="report-header">

            <div class="report-logo-area">

                <img src="assets/images/logo uitm.png" class="report-logo" alt="UiTM Logo">

            </div>

            <div class="report-header-text">

                <h1>Universiti Teknologi MARA</h1>

                <h2>CampusEvent Management System</h2>

                <p>
                    Student Club Event & Proposal Management System
                </p>

            </div>

            <div class="report-number">

                <strong>Report No.</strong>

                <span>
                    <?php echo htmlspecialchars($reportNumber); ?>
                </span>

            </div>

        </header>

        <section class="report-title">

            <h2>Event Performance Report</h2>

            <p>
                Official event report generated by the CampusEvent system
            </p>

        </section>

        <div class="report-status-line">

            <span class="report-status-badge report-status-<?php
            echo htmlspecialchars($statusClass);
            ?>">
                <?php echo htmlspecialchars($reportStatus); ?>
            </span>

        </div>

        <!-- EVENT INFORMATION -->

        <h3 class="report-section-title">
            1. Event Information
        </h3>

        <table class="report-info-table">

            <tr>
                <th>Report Number</th>

                <td>
                    <?php echo htmlspecialchars($reportNumber); ?>
                </td>
            </tr>

            <tr>
                <th>Event Name</th>

                <td>
                    <?php echo htmlspecialchars($event['event_name']); ?>
                </td>
            </tr>

            <tr>
                <th>Club Name</th>

                <td>
                    <?php
                    echo !empty($event['club_name'])
                        ? htmlspecialchars($event['club_name'])
                        : '-';
                    ?>
                </td>
            </tr>

            <tr>
                <th>Event Date</th>

                <td>
                    <?php
                    echo date(
                        "d F Y",
                        strtotime($event['event_date'])
                    );
                    ?>
                </td>
            </tr>

            <tr>
                <th>Event Time</th>

                <td>
                    <?php
                    echo date(
                        "h:i A",
                        strtotime($event['event_time'])
                    );
                    ?>
                </td>
            </tr>

            <tr>
                <th>Location</th>

                <td>
                    <?php echo htmlspecialchars($event['location']); ?>
                </td>
            </tr>

            <tr>
                <th>Estimated Budget</th>

                <td>
                    RM <?php
                    echo number_format(
                        (float) $event['budget'],
                        2
                    );
                    ?>
                </td>
            </tr>

            <tr>
                <th>Student Event Fee</th>

                <td>
                    <?php
                    echo (float) $event['event_fee'] > 0
                        ? 'RM ' . number_format(
                            (float) $event['event_fee'],
                            2
                        )
                        : 'Free';
                    ?>
                </td>
            </tr>

            <tr>
                <th>Event Status</th>

                <td>
                    <?php echo htmlspecialchars($event['status']); ?>
                </td>
            </tr>

            <tr>
                <th>Report Status</th>

                <td>
                    <?php echo htmlspecialchars($reportStatus); ?>
                </td>
            </tr>

        </table>

        <!-- PARTICIPATION SUMMARY -->

        <h3 class="report-section-title">
            2. Participation Summary
        </h3>

        <div class="report-summary-grid">

            <div class="report-summary-box">

                <strong>
                    <?php echo $totalParticipants; ?>
                </strong>

                <span>Total Registered</span>

            </div>

            <div class="report-summary-box">

                <strong>
                    <?php echo $totalAttended; ?>
                </strong>

                <span>Attended</span>

            </div>

            <div class="report-summary-box">

                <strong>
                    <?php echo $totalAbsent; ?>
                </strong>

                <span>Absent</span>

            </div>

            <div class="report-summary-box">

                <strong>
                    <?php echo $attendanceRate; ?>%
                </strong>

                <span>Attendance Rate</span>

            </div>

        </div>

        <div class="report-payment-summary">

            <div>
                <strong><?php echo $totalPaid; ?></strong>
                <span>Paid</span>
            </div>

            <div>
                <strong><?php echo $totalPendingPayment; ?></strong>
                <span>Pending Payment</span>
            </div>

            <div>
                <strong><?php echo $totalFailedPayment; ?></strong>
                <span>Failed Payment</span>
            </div>

            <div>
                <strong><?php echo $totalRegistered; ?></strong>
                <span>Not Marked Attendance</span>
            </div>

        </div>

        <!-- EVENT DESCRIPTION -->

        <h3 class="report-section-title">
            3. Event Description
        </h3>

        <div class="report-text-section">

            <?php
            echo !empty($event['description'])
                ? nl2br(htmlspecialchars($event['description']))
                : 'No event description was provided.';
            ?>

        </div>

        <!-- REPORT SUMMARY -->

        <h3 class="report-section-title">
            4. Report Summary
        </h3>

        <div class="report-text-section">

            <?php
            echo !empty($event['report_summary'])
                ? nl2br(htmlspecialchars($event['report_summary']))
                : 'No report summary has been provided.';
            ?>

        </div>

        <?php
        $sectionNumber = 5;
        ?>

        <!-- ADMIN REMARK -->

        <?php if (!empty($event['report_remark'])) { ?>

            <h3 class="report-section-title">
                <?php echo $sectionNumber++; ?>. Administrator Remark
            </h3>

            <div class="report-text-section report-remark-section">

                <?php
                echo nl2br(
                    htmlspecialchars($event['report_remark'])
                );
                ?>

            </div>

        <?php } ?>

        <!-- PARTICIPANT LIST -->

        <h3 class="report-section-title">
            <?php echo $sectionNumber++; ?>. Participant List
        </h3>

        <?php if (count($participants) > 0) { ?>

            <table class="report-participant-table">

                <thead>

                    <tr>
                        <th>No.</th>
                        <th>Participant Name</th>
                        <th>Matric No.</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Payment</th>
                        <th>Attendance</th>
                    </tr>

                </thead>

                <tbody>

                    <?php
                    $participantNo = 1;

                    foreach ($participants as $participant) {
                        ?>

                        <tr>

                            <td>
                                <?php echo $participantNo++; ?>
                            </td>

                            <td>
                                <?php
                                echo htmlspecialchars(
                                    $participant['full_name']
                                );
                                ?>
                            </td>

                            <td>
                                <?php
                                echo htmlspecialchars(
                                    $participant['matric_no']
                                );
                                ?>
                            </td>

                            <td>
                                <?php
                                echo htmlspecialchars(
                                    $participant['email']
                                );
                                ?>
                            </td>

                            <td>
                                <?php
                                echo htmlspecialchars(
                                    $participant['phone']
                                );
                                ?>
                            </td>

                            <td>

                                <strong>
                                    <?php
                                    echo htmlspecialchars(
                                        $participant['payment_status']
                                    );
                                    ?>
                                </strong>

                                <?php if (!empty($participant['payment_method'])) { ?>

                                    <br>

                                    <small>
                                        <?php
                                        echo htmlspecialchars(
                                            $participant['payment_method']
                                        );
                                        ?>
                                    </small>

                                <?php } ?>

                            </td>

                            <td>
                                <?php
                                echo htmlspecialchars(
                                    $participant['attendance_status']
                                );
                                ?>
                            </td>

                        </tr>

                    <?php } ?>

                </tbody>

            </table>

        <?php } else { ?>

            <div class="report-empty-participant">
                No participant has registered for this event.
            </div>

        <?php } ?>

        <!-- EVENT POSTER -->

        <section class="report-poster-section">

            <h3 class="report-section-title">
                <?php echo $sectionNumber++; ?>. Event Poster
            </h3>

            <?php if ($posterPath !== "") { ?>

                <img src="<?php echo $posterPath; ?>" class="report-poster" alt="Event Poster">

            <?php } else { ?>

                <div class="report-poster-empty">
                    No event poster has been uploaded.
                </div>

            <?php } ?>

        </section>

        <!-- APPROVAL SECTION -->

        <h3 class="report-section-title">
            <?php echo $sectionNumber++; ?>. Verification
        </h3>

        <table class="report-approval-table">

            <tr>

                <td>

                    <span class="report-signature-line"></span>

                    <div class="report-signature-text">

                        Prepared / Submitted By

                        <br>

                        <strong>
                            <?php
                            echo !empty($event['club_name'])
                                ? htmlspecialchars($event['club_name'])
                                : 'Club Representative';
                            ?>
                        </strong>

                        <br><br>

                        Date: __________________

                    </div>

                </td>

                <td>

                    <span class="report-signature-line"></span>

                    <div class="report-signature-text">

                        Reviewed / Approved By

                        <br>

                        <strong>CampusEvent Administrator</strong>

                        <br><br>

                        Date: __________________

                    </div>

                </td>

            </tr>

        </table>

        <footer class="report-footer">

            <div>
                Generated by:
                <?php echo htmlspecialchars($generatedBy); ?>
            </div>

            <div>
                Generated on:
                <?php echo htmlspecialchars($generatedDate); ?>
            </div>

        </footer>

    </main>

</body>

</html>